# Generated by Django 4.0.6 on 2023-02-07 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_regex', message='Use correct phone number.', regex='[+]\\d{1,3}[(]\\d{3}[)]\\d{3}[-]\\d{2}[-]\\d{2}')], verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('type_error', models.CharField(choices=[('DE', 'Description error'), ('CDE', 'Combat data error'), ('NE', 'Name error'), ('IE', 'Image error'), ('FDE', 'Front display error'), ('OE', 'Other error')], default='OE', max_length=200, verbose_name='Type')),
                ('text_error', models.CharField(max_length=202, verbose_name='Text')),
            ],
        ),
    ]
